# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Blogs.Tags'),
        ),
    ]
