# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_auto_20170420_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
