# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_auto_20170422_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
