# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_blog_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isTut',
            field=models.BooleanField(default=False),
        ),
    ]
