# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 16:38
from __future__ import unicode_literals

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20170420_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=User.models.get_image_path),
        ),
    ]
