# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 09:56
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_profile_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_image', '700x700', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
