# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20170421_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
